services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: team-mssql
    ports:
      - "${DB_PORT:-1433}:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql
      - ./db:/db:ro
volumes:
  mssql_data: